# train.py: Script for training a model using the dataset generated by the previous script.
# This script takes arguments to specify the dataset and other configurations.

import gc
from datetime import datetime
from pathlib import Path

import hydra
import torch
from dotenv import load_dotenv
from omegaconf import DictConfig, OmegaConf
from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed

import wandb
from hypersteer import get_model
from hypersteer.data import get_dataset_factory
from hypersteer.scripts.evaluate import run_eval
from hypersteer.scripts.inference import run_inference
from hypersteer.training import Trainer
from hypersteer.utils.configs import ExperimentConfig, config_to_pydantic
from hypersteer.utils.helpers import (
    configure_tokenizer_model,
    destroy_process_group,
    get_logger,
)

# Initialize the logger
logger = get_logger(__name__)


@hydra.main(config_path="../../config", config_name="config", version_base=None)
def main(cfg: DictConfig):
    # Use experiment config if it exists, otherwise use the main config
    config = cfg.experiment if hasattr(cfg, "experiment") else cfg

    # Handle pretrained config merging if needed
    if config.dump_dir:
        pretrained_cfg_path = Path(config.dump_dir) / "config.yaml"
        if pretrained_cfg_path.exists():
            logger.info(f"Loading pretrained config from {pretrained_cfg_path}")
            pretrained_cfg = OmegaConf.load(pretrained_cfg_path)
            config = OmegaConf.merge(pretrained_cfg, config)

    # Convert to pydantic config
    args = config_to_pydantic(config, ExperimentConfig)

    # Set the device for this process
    device = torch.cuda.current_device()
    logger.debug(f"Using device {device}")

    # Set a unique seed per rank for reproducibility
    set_seed(args.seed)

    run_name = datetime.now().strftime("train_%Y%m%d_%H%M%S%f")
    if args.train.resume_from and not args.dump_dir:
        # Continue in the same run dir (<run>/train/checkpoints/step_N) so checkpoints
        # and HF uploads stay under one run name
        args.dump_dir = Path(args.train.resume_from).resolve().parents[2]
        run_name = args.dump_dir.name
        logger.info(f"Resuming run {run_name} from {args.train.resume_from}")
    if args.dump_dir:
        args.dump_dir = Path(args.dump_dir)
    if not args.dump_dir and not args.debug:
        args.dump_dir = Path(args.train.save_dir) / run_name
        (args.dump_dir / "train").mkdir(parents=True, exist_ok=True)

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        args.model.target_model_name,
        model_max_length=512,
    )
    tokenizer.padding_side = "right"

    # Load model instance onto device
    if args.train.use_bf16:
        logger.info(f"Using bfloat16 for model {args.model.model_name}")
    model_instance = AutoModelForCausalLM.from_pretrained(
        args.model.target_model_name,
        torch_dtype=torch.bfloat16 if args.train.use_bf16 else None,
    )
    model_instance = model_instance.eval()
    model_instance.to(device)

    configure_tokenizer_model(model_instance, tokenizer)

    # Use train config for training dataset
    factory = get_dataset_factory(
        args.dataset.dataset_type,
        model=model_instance,
        tokenizer=tokenizer,
        dump_dir=args.dump_dir,
        dataset_category="instruction",  # or as needed
        num_of_examples=args.dataset.train.num_of_examples,
        output_length=args.inference.steering_output_length,
    )
    training_dataset = factory.create_training_ds(
        dataset_name=args.dataset.train.hf_dataset_name,
        data_files=args.dataset.train.hf_data_files,
        split=args.dataset.train.hf_split,
        cache_dir=args.dataset.train.cache_dir,
        binarize=args.train.binarize_dataset,
        train_on_negative=args.train.train_on_negative,
        output_length=args.inference.steering_output_length,
        max_num_of_examples=args.dataset.train.num_of_examples,
        negative_example_ratio=args.train.negative_example_ratio,
        replace_negative_description=True,
        select_concept_ids=args.dataset.train.select_concept_ids,
        max_concepts=args.dataset.train.max_concepts,
    )

    logger.info(f"Loaded and processed dataset with {len(training_dataset)} examples")

    combined_df = training_dataset.to_pandas()

    # Get concept IDs from the dataset
    concept_ids = list(set(combined_df.get("concept_id", [0])))
    concept_ids = [cid for cid in concept_ids if cid >= 0]

    if not args.debug:
        OmegaConf.save(
            OmegaConf.create(args.model_dump()),
            args.dump_dir / "config.yaml",
        )

    # Training logic
    _logged_code = False
    model_config = args.model
    training_args = args.train

    logger.info(f"Training {model_config.model_name} with {len(concept_ids)} concepts")

    if training_args.train_on_negative:
        logger.info(f"Training {model_config.model_name} on negative examples")

    # Create in-train dev set
    dev_size = (
        int(args.dataset.train.dev_size * len(combined_df))
        if 0 < args.dataset.train.dev_size < 1
        else min(int(args.dataset.train.dev_size), len(combined_df) // 5)
    )

    # Shuffle the dataframe before splitting
    combined_df = combined_df.sample(
        frac=1,
        random_state=training_args.seed,
    ).reset_index(drop=True)
    # Split into train and dev sets
    train_df = combined_df.iloc[dev_size:]
    dev_df = combined_df.iloc[:dev_size]

    logger.info(
        f"Training on {len(train_df)} examples, validating on {len(dev_df)} examples",
    )

    # Create model instance
    benchmark_model = get_model(
        model_config.model_name,
        model=model_instance,
        tokenizer=tokenizer,
        training_args=training_args,
        model_config=model_config,
        wandb_config=args.wandb,
        device=device,
        seed=training_args.seed,
        dump_dir=args.dump_dir / "train" if args.dump_dir else None,
    )

    benchmark_model.make_model(
        mode="train",
        low_rank_dimension=model_config.low_rank_dimension or 1,
        dtype=torch.bfloat16 if training_args.use_bf16 else None,
    )

    if training_args.use_bf16:
        benchmark_model.ax.to(torch.bfloat16)

    # Create dataloaders
    train_dataloader, train_sampler = benchmark_model.make_dataloader(train_df)

    dev_dataloader = None
    if len(dev_df) > 0:
        dev_dataloader, _ = benchmark_model.make_dataloader(
            dev_df,
            shuffle=False,
        )

    # Initialize wandb
    if args.wandb.log and not args.debug:
        wandb.init(
            project=args.wandb.project,
            entity=args.wandb.entity,
            tags=args.wandb.tags,
            group=args.wandb.group,
            notes=args.wandb.notes,
            name=f"{model_config.model_name}_{run_name}",
            config={
                "experiment": args.model_dump(),
                "model": model_config.model_dump(),
                "training": training_args.model_dump(),
            },
        )
        if args.wandb.log_code and not _logged_code:
            wandb.run.log_code(Path(__file__).parent.parent)
            _logged_code = True

    trainer = Trainer(
        model=benchmark_model,
        training_args=training_args,
        model_config=model_config,
        wandb_config=args.wandb,
    )

    torch.cuda.empty_cache()
    trainer.train(train_dataloader, dev_dataloader, train_sampler)

    # Save model
    if not args.debug:
        benchmark_model.save(
            args.dump_dir / "train", model_name=model_config.model_name
        )
        logger.debug(f"Saved weights for model {model_config.model_name}")

    # Clean up
    del benchmark_model, trainer
    gc.collect()
    torch.cuda.empty_cache()

    destroy_process_group()

    if training_args.run_eval_suite_at_end and not args.debug:
        if not args.inference.factor_selection.enable:
            infer_run = run_inference(args)
            run_eval(args, infer_run=infer_run)
        else:
            run_inference(args)


if __name__ == "__main__":
    # torch.autograd.set_detect_anomaly(True)  # debug-only; slows training several-fold
    load_dotenv(override=True)
    main()
