defaults:
  - base

dataset_type: "axbench"

# AxBench-specific overrides
train:
  dataset_category: "instruction"
  max_concepts: 50
  num_of_examples: -1
  cache_dir: "assets/cache"
  hf_dataset_name: "pyvene/axbench-concept500"
  hf_data_files:
    train: "2b/l20/train/data.parquet"
  hf_split: "train"
  select_concept_ids: []
  use_split: false
eval:
  dataset_category: "instruction"
  max_concepts: -1
  num_of_examples: -1
  cache_dir: "assets/cache"
  hf_dataset_name: "pyvene/axbench-concept10"
  hf_data_files:
    train: "2b/l20/train/data.parquet"
  hf_split: "train"
  select_concept_ids: []
  use_split: false