defaults:
  - _self_

train:
  dataset_name: null
  dataset_category: "instruction"
  dataset_split: "train"
  task_name: null
  concept_path: null
  max_concepts: 500
  num_of_examples: 144
  filter_length: 512
  master_data_dir: null
  shuffle: true
  dev_size: 0.1
  select_column: "prompt"
  response_column: "completion"
  cache_dir: null
  select_concept_ids: []
  held_out_eval: false
  input_condition_concept: false
  max_seq_length: null
  hf_dataset_name: null
  hf_data_files: null
  hf_split: "train"
  hf_cache_dir: null
  hf_revision: null
  hf_use_auth_token: null
  hf_streaming: false
  hf_num_proc: null
  hf_keep_in_memory: false
  hf_download_config: null
  hf_download_mode: null
  hf_verification_mode: null
  hf_ignore_verifications: false
  hf_save_infos: false
  hf_trust_remote_code: false
  use_split: false

eval:
  dataset_name: null
  dataset_category: "instruction"
  dataset_split: "eval"
  task_name: null
  concept_path: null
  max_concepts: 500
  num_of_examples: 144
  filter_length: 512
  master_data_dir: null
  shuffle: true
  dev_size: 0.1
  select_column: "prompt"
  response_column: "completion"
  cache_dir: null
  select_concept_ids: []
  held_out_eval: false
  input_condition_concept: false
  max_seq_length: null
  hf_dataset_name: null
  hf_data_files: null
  hf_split: "eval"
  hf_cache_dir: null
  hf_revision: null
  hf_use_auth_token: null
  hf_streaming: false
  hf_num_proc: null
  hf_keep_in_memory: false
  hf_download_config: null
  hf_download_mode: null
  hf_verification_mode: null
  hf_ignore_verifications: false
  hf_save_infos: false
  hf_trust_remote_code: false
  use_split: false
